name: 'Affected projects'
description: 'Get affected projects in a monorepo by git'
author: 'AlekseyLeshko <alekseyleshko@gmail.com>'
inputs:
  workspaces:
    required: true
    description: 'Enter workspaces'
  default_workspaces:
    description: 'Enter default workspaces'
  filter_pattern:
    description: 'Filter projects by pattern'
    default: '**'
outputs:
  affected_workspaces:
    description: 'Array of affected workspaces in a monorepo'
runs:
  using: 'node16'
  main: 'dist/index.js'
