name: 'Affected projects'
description: 'Get affected projects in a monorepo by git'
author: 'AlekseyLeshko <alekseyleshko@gmail.com>'
inputs:
  workspaces:
    required: true
    description: 'Enter workspaces'
  filter_pattern:
    description: 'Filter projects by pattern'
  # default_projects:
    # description: 'Enter default project array in your workspaces'
runs:
  using: 'node16'
  main: 'dist/index.js'
